apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapp-deployment-3000
spec:
  selector:
    matchLabels:
      app: notes
  replicas: 3
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notesserver
        image: us-central1-docker.pkg.dev/absolute-accord-378620/test-repo/cd:9be9549187feae6f29a0a7ce8a7eff47ada8b4e8
        env:
        - name: "PORT"
          value: "3000"